name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: Setup pnpm
        run: |
          npm install --global pnpm
      - name: Fetching node modules
        run: |
          pnpm install
          cd ..
      - name: Build distributable
        run: |
          pnpm build
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'dist'
          path: |
            dist/
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Gathering artifacts
        run: |
          cd artifacts
          for name in *
          do
              tar -cJvf ../$name.tar.xz -C $name/ .
          done
          cd ..
          rm -rf artifacts
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: latest
          files: |
            *
